#!/usr/bin/env python3
"""
Merge all PPE source datasets and build train/valid/test splits for each model.

Three separate 2-class datasets are built:
  dataset/ppe_mask/       (mask=0, no_mask=1)
  dataset/ppe_headcover/  (headcover=0, no_headcover=1)
  dataset/ppe_gloves/     (no_gloves=0, gloves=1)

Source routing (which source folders feed which model):
  mask model:      rf_mask_militech, rf_mask_joseph, kaggle_mask_labeled,
                   kaggle_mask_andrewmvd_yolo
  headcover model: rf_hairnet_maha, rf_headcover_protection
  gloves model:    rf_gloves_ppe, rf_gloves_medical

Split ratios (default): train 70% / valid 20% / test 10%

Deduplication: images with the same filename stem are deduplicated
(keeping first occurrence). This avoids the same image appearing in
multiple sources.

Usage:
  python scripts/ppe_build_split.py
  python scripts/ppe_build_split.py --val 0.15 --test 0.10
  python scripts/ppe_build_split.py --model mask   # rebuild only mask model
  python scripts/ppe_build_split.py --dry-run
"""
from __future__ import annotations

import argparse
import random
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES_DIR = ROOT / "dataset" / "ppe_sources"
DATASET_ROOT = ROOT / "dataset"

IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

# ─── Source routing: model → list of source folder names ──────────────────────
MODEL_SOURCES: dict[str, list[str]] = {
    "mask": [
        "rf_mask_militech",
        "rf_mask_joseph",
        "kaggle_mask_labeled",          # from ppe_autolabel_faces.py
        "kaggle_mask_andrewmvd_yolo",   # from ppe_convert_voc.py
    ],
    "headcover": [
        "rf_hairnet_maha",
        "rf_headcover_protection",
    ],
    "gloves": [
        "rf_gloves_ppe",
        "rf_gloves_medical",
    ],
}

# ─── Canonical class names per model ──────────────────────────────────────────
MODEL_CLASSES: dict[str, dict[str, str]] = {
    "mask":      {"names": "mask,no_mask",           "nc": 2},
    "headcover": {"names": "headcover,no_headcover",  "nc": 2},
    "gloves":    {"names": "no_gloves,gloves",        "nc": 2},
}


def _collect_image_label_pairs(source_folder: Path) -> list[tuple[Path, Path]]:
    """Find all (image, label) pairs in a Roboflow-style or flat source folder."""
    pairs: list[tuple[Path, Path]] = []

    def _search(img_dir: Path, lbl_dir: Path) -> None:
        if not img_dir.is_dir() or not lbl_dir.is_dir():
            return
        for img in sorted(img_dir.iterdir()):
            if img.suffix.lower() not in IMAGE_EXT:
                continue
            lbl = lbl_dir / f"{img.stem}.txt"
            if lbl.is_file():
                pairs.append((img, lbl))

    # Roboflow layout: source/{train,valid,test}/images + labels
    for split in ("train", "valid", "test"):
        _search(source_folder / split / "images", source_folder / split / "labels")

    # Flat layout: source/images + labels
    if not pairs:
        _search(source_folder / "images", source_folder / "labels")

    # Class-subfolder layout: source/{class}/images + labels
    if not pairs:
        for class_dir in sorted(source_folder.iterdir()):
            if class_dir.is_dir() and class_dir.name not in ("images", "labels", "train", "valid", "test"):
                _search(class_dir / "images", class_dir / "labels")

    return pairs


def _copy_pair(img: Path, lbl: Path, dest_img: Path, dest_lbl: Path) -> None:
    dest_img.parent.mkdir(parents=True, exist_ok=True)
    dest_lbl.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(img, dest_img)
    shutil.copy2(lbl, dest_lbl)


def _write_data_yaml(out_dir: Path, model: str) -> None:
    info = MODEL_CLASSES[model]
    names_list = info["names"].split(",")
    nc = info["nc"]
    names_yaml = "\n".join(f"  {i}: {n}" for i, n in enumerate(names_list))
    yaml_text = f"""\
# PPE {model} detection dataset
# Generated by ppe_build_split.py
path: {out_dir}
train: images/train
val:   images/valid
test:  images/test

nc: {nc}
names:
{names_yaml}
"""
    (out_dir / "data.yaml").write_text(yaml_text, encoding="utf-8")


def build_model_dataset(
    model: str,
    *,
    val_ratio: float,
    test_ratio: float,
    seed: int,
    dry_run: bool,
) -> dict[str, int]:
    rng = random.Random(seed)
    out_dir = DATASET_ROOT / f"ppe_{model}"
    sources = MODEL_SOURCES.get(model, [])

    all_pairs: list[tuple[Path, Path]] = []
    seen_stems: set[str] = set()

    for src_name in sources:
        src_folder = SOURCES_DIR / src_name
        if not src_folder.is_dir():
            print(f"  [{model}] source not found (skip): {src_name}")
            continue
        src_pairs = _collect_image_label_pairs(src_folder)
        deduped = 0
        for img, lbl in src_pairs:
            stem = img.stem
            if stem in seen_stems:
                deduped += 1
                continue
            seen_stems.add(stem)
            all_pairs.append((img, lbl))
        print(f"  [{model}/{src_name}] {len(src_pairs)} pairs  (deduped {deduped})")

    if not all_pairs:
        print(f"  [{model}] No labeled pairs found. Check source downloads.")
        return {"total": 0, "train": 0, "valid": 0, "test": 0}

    # Shuffle and split
    rng.shuffle(all_pairs)
    n = len(all_pairs)
    n_test = max(1, int(round(n * test_ratio))) if n > 2 else 0
    n_val  = max(1, int(round(n * val_ratio)))  if n > 2 else 0
    n_train = n - n_val - n_test

    splits = (
        ("test",  all_pairs[:n_test]),
        ("valid", all_pairs[n_test:n_test + n_val]),
        ("train", all_pairs[n_test + n_val:]),
    )

    if not dry_run:
        # Clear existing splits
        for split, _ in splits:
            for sub in ("images", "labels"):
                d = out_dir / sub / split
                if d.is_dir():
                    shutil.rmtree(d)
                d.mkdir(parents=True, exist_ok=True)

    for split, pairs in splits:
        for img, lbl in pairs:
            dest_img = out_dir / "images" / split / img.name
            dest_lbl = out_dir / "labels" / split / f"{img.stem}.txt"
            if not dry_run:
                _copy_pair(img, lbl, dest_img, dest_lbl)

    if not dry_run:
        _write_data_yaml(out_dir, model)

    print(
        f"  [{model}] total={n}  train={n_train}  valid={n_val}  test={n_test}"
        + ("  (dry-run)" if dry_run else f"  → {out_dir}")
    )
    return {"total": n, "train": n_train, "valid": n_val, "test": n_test}


def main() -> int:
    parser = argparse.ArgumentParser(description="Build per-model PPE train/valid/test splits")
    parser.add_argument("--model", choices=["mask", "headcover", "gloves", "all"], default="all")
    parser.add_argument("--val",  type=float, default=0.20, help="Validation fraction (default 0.20)")
    parser.add_argument("--test", type=float, default=0.10, help="Test fraction (default 0.10)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.val + args.test >= 1.0:
        print("ERROR: val + test must be < 1.0", file=sys.stderr)
        return 1

    if not SOURCES_DIR.is_dir():
        print(f"Sources not found: {SOURCES_DIR}", file=sys.stderr)
        print("Run ppe_download_datasets.py first.", file=sys.stderr)
        return 1

    models = list(MODEL_SOURCES.keys()) if args.model == "all" else [args.model]

    if args.dry_run:
        print("(dry-run — no files copied)")

    print(f"\nBuilding PPE datasets (val={args.val:.0%} test={args.test:.0%})\n")
    for model in models:
        build_model_dataset(model, val_ratio=args.val, test_ratio=args.test,
                            seed=args.seed, dry_run=args.dry_run)

    if not args.dry_run:
        print("\nDataset YAMLs written:")
        for model in models:
            yaml = DATASET_ROOT / f"ppe_{model}" / "data.yaml"
            if yaml.is_file():
                print(f"  {yaml}")
        print("\nNext: python scripts/ppe_train_all.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
